console.log('Data.js loading...');

class WikiData {
    static pools = {
        cities: {
            US: [
                "Portland, Oregon", "Seattle, Washington",
                "Brooklyn, New York", "Austin, Texas", 
                "Chicago, Illinois", "Los Angeles, California",
                "Philadelphia, Pennsylvania", "Oakland, California",
                "Minneapolis, Minnesota", "Providence, Rhode Island",
                "Worcester, Massachusetts", "Richmond, Virginia",
                "Olympia, Washington", "Baltimore, Maryland",
                "New Haven, Connecticut", "Cleveland, Ohio",
                "Detroit, Michigan", "Pittsburgh, Pennsylvania", 
                "Burlington, Vermont", "Asheville, North Carolina",
                "Reykjavik, Iceland",
                "Marrakech, Morocco", 
                "Kathmandu, Nepal",
                "Ulaanbaatar, Mongolia",
                "Thessaloniki, Greece",
                "Dubrovnik, Croatia",
                "Zanzibar, Tanzania",
                "Cusco, Peru",
                "Kyoto, Japan",
                "Tbilisi, Georgia",
                "Valparaiso, Chile",
                "Cartagena, Colombia",
                "Bucharest, Romania",
                "Ljubljana, Slovenia",
                "Chiang Mai, Thailand",
                "Porto, Portugal",
                "Krakow, Poland",
                "Tallinn, Estonia",
                "Albuquerque, New Mexico",
                "Anchorage, Alaska",
                "Asheville, North Carolina",
                "Boise, Idaho",
                "Burlington, Vermont",
                "Charleston, South Carolina",
                "Chattanooga, Tennessee",
                "Cincinnati, Ohio",
                "Dayton, Ohio",
                "Des Moines, Iowa",
                "Durham, North Carolina",
                "Eugene, Oregon",
                "Fort Collins, Colorado",
                "Fort Worth, Texas",
                "Fresno, California",
                "Grand Rapids, Michigan",
                "Greensboro, North Carolina",
                "Hartford, Connecticut",
                "Indianapolis, Indiana",
                "Jacksonville, Florida",
                "Kansas City, Missouri",
                "Knoxville, Tennessee",
                "Little Rock, Arkansas",
                "Louisville, Kentucky",
                "Madison, Wisconsin",
                "Memphis, Tennessee",
                "Milwaukee, Wisconsin",
                "Minneapolis, Minnesota",
                "Nashville, Tennessee",
                "New Orleans, Louisiana",
                "Oakland, California",
                "Omaha, Nebraska",
                "Orlando, Florida",
                "Pittsburgh, Pennsylvania",
                "Providence, Rhode Island",
                "Raleigh, North Carolina",
                "Richmond, Virginia",
                "Rochester, New York",
                "Sacramento, California",
                "Salt Lake City, Utah",
                "San Antonio, Texas",
                "San Jose, California",
                "Savannah, Georgia",
                "Spokane, Washington",
                "Springfield, Missouri",
                "St. Louis, Missouri",
                "Syracuse, New York",
                "Tacoma, Washington",
                "Tampa, Florida",
                "Toledo, Ohio",
                "Tucson, Arizona",
                "Tulsa, Oklahoma",
                "Wichita, Kansas"
            ]
        },
        genres: {
            metal: [
                "Death Metal", "Black Metal", "Doom Metal",
                "Sludge Metal", "Post-Metal", "Grindcore",
                "Blackened Crust", "Funeral Doom",
                "Atmospheric Black Metal", "Death-Doom",
                "Technical Death Metal", "Melodic Black Metal",
                "Blackened Death Metal", "Progressive Metal",
                "Stoner Metal", "Drone Metal",
                "Blackgaze",
                "Post-Metal",
                "Drone",
                "Sludge",
                "Mathcore",
                "Folk Metal",
                "Industrial",
                "Symphonic",
                "Gothic",
                "Prog",
                "Tech Death",
                "Melodeath",
                "Deathcore",
                "Crossover",
                "Thrashcore"
            ],
            experimental: [
                "Noise Rock", "Industrial", "Drone",
                "Avant-garde Metal", "Progressive Metal",
                "Post-Hardcore", "Math Rock",
                "Experimental Rock", "Power Electronics",
                "Dark Ambient", "Harsh Noise",
                "No Wave", "Free Jazz Metal",
                "Industrial Noise", "Musique Concrète"
            ]
        },
        labels: [
            "Relapse Records", "Southern Lord", "Profound Lore", "The Flenser",
            "Neurot Recordings", "Hydra Head", "Ipecac Recordings", "Thrill Jockey",
            "Three One G", "Deathwish Inc.", "20 Buck Spin", "Translation Loss",
            "Sargent House", "Sacred Bones", "Gilead Media", "Throatruiner Records",
            "Roadburn Records", "Hypertension Records", "Torture Garden Records",
            "Nuclear War Now!", "Iron Lung Records", "Gravity Records",
            "Alternative Tentacles", "Load Records", "Hospital Productions",
            "Handmade Birds", "Crucial Blast",
            "Profound Lore",
            "Nuclear Blast",
            "Season of Mist",
            "Relapse",
            "Earache",
            "Peaceville",
            "Rise Above",
            "Southern Lord",
            "Candlelight",
            "Century Media",
            "Metal Blade",
            "Roadrunner",
            "Napalm",
            "Prosthetic"
        ],
        names: {
            first: [
                "John", "Mike", "David", "Chris", "James",
                "Sarah", "Emma", "Alex", "Sam", "Dan", 
                "Steve", "Tom", "Paul", "Kevin", "Rob",
                "Erik", "Justin", "Ryan", "Matt", "Josh",
                "Brandon", "Seth", "Aaron", "Blake", "Scott",
                "Dylan", "Keith", "Greg", "Trevor", "Zack",
                "Nathan", "Jason", "Brian", "Kyle", "Eric",
                "Magdalena", "Mazikeen", "Belle", "Kadence", "Serenity",
                "Aurora", "Luna", "Nova", "Athena", "Iris", "Eden", "Sage",
                "Astrid", "Calliope", "Dahlia", "Echo", "Freya",
                "Gwendolyn", "Juniper", "Maeve", "Persephone", "Rhiannon",
                "Selene", "Thalia", "Vesper", "Zinnia",
                "Akiko", "Hiroshi", "Kenji", "Yuki", "Sakura",
                "Wei", "Jing", "Ming", "Li", "Hui",
                "José", "Carlos", "Miguel", "Sofia", "Isabella",
                "Mohammed", "Ahmed", "Fatima", "Aisha", "Omar",
                "Priya", "Raj", "Arun", "Deepa", "Arjun",
                "Olga", "Ivan", "Dmitri", "Natasha", "Boris",
                "Klaus", "Hans", "Friedrich", "Helga", "Wolfgang",
                "Jean", "Pierre", "Marie", "Claude", "François",
                "Giuseppe", "Marco", "Sofia", "Luca", "Antonio",
                "Thor", "Bjorn", "Astrid", "Erik", "Freya",
                "Mátyás", "István", "Zoltán", "Ferenc", "János",
                "Saoirse", "Siobhan", "Aoife", "Niamh", "Eoin",
                "Yara", "Zain", "Malik", "Noor", "Rami",
                "Kwame", "Chidi", "Olayinka", "Folami", "Babajide",
                "Isolde", "Lysandra", "Nephele", "Ondine", "Pandora",
                "Thessaly", "Xiomara", "Yseult", "Zephyr", "Avalon"
            ],
            last: [
                "Smith", "Johnson", "Williams", "Brown", "Jones",
                "Garcia", "Miller", "Davis", "Wilson", "Anderson",
                "Taylor", "Moore", "Jackson", "Martin", "Lee",
                "Thompson", "White", "Harris", "Clark", "Lewis",
                "Young", "Hall", "Walker", "Allen", "King",
                "Wright", "Hill", "Scott", "Green", "Adams",
                "Baker", "Nelson", "Carter", "Mitchell", "Roberts",
                "Cooper", "Morgan", "Murphy", "Rogers", "Cook",
                "Peterson", "Bailey", "Reed", "Kelly", "Howard",
                "Kim", "Park", "Lee", "Choi", "Jung",
                "Wang", "Li", "Zhang", "Liu", "Chen",
                "Singh", "Patel", "Kumar", "Shah", "Sharma",
                "Ivanov", "Petrov", "Smirnov", "Kuznetsov", "Popov",
                "Müller", "Schmidt", "Fischer", "Weber", "Meyer",
                "Dubois", "Bernard", "Thomas", "Petit", "Durand",
                "Rossi", "Ferrari", "Russo", "Esposito", "Romano",
                "Kowalski", "Nowak", "Wojcik", "Kowalczyk", "Kaminski",
                "Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson",
                "O'Connor", "Murphy", "Kelly", "O'Brien", "Ryan",
                "Papadopoulos", "Dimitriou", "Nikolaou", "Georgiou", "Constantinou",
                "Santos", "Silva", "Ferreira", "Pereira", "Costa",
                "Nagy", "Kovács", "Tóth", "Szabó", "Horváth",
                "Petrosyan", "Makowski", "Lambert", "Medema", "Caldwell",
                "Thordendal", "Bergeron", "Balderaz", "Ryerson", "Gallaway",
                "Stanza", "Dwyer", "Alaric", "Caspian", "Drake",
                "Evander", "Griffin", "Hawthorne", "Jasper", "Leander",
                "Magnus", "Orion", "Phoenix", "Quentin", "Thorne",
                "Xavier", "Blackwood", "Crowley", "Darkholme", "Frost",
                "Grimm", "Ironside", "Nightshade", "Ravencroft", "Shadowmend",
                "Thornheart", "Winterborn", "Wolfsbane", "Doomforge", "Stormwind",
                "Blackthorn", "Ravenscroft", "Dreadmore", "Shadowvale", "Moonscar",
                "Bloodworth", "Steelclaw", "Frostfang", "Stormrage", "Darkmane",
                "Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe",
                "Hassan", "Ahmed", "Mohamed", "Ali", "Ibrahim",
                "Cohen", "Levy", "Mizrahi", "Peretz", "Friedman",
                "Nguyen", "Tran", "Pham", "Le", "Vu",
                "Jansen", "De Jong", "Van Dijk", "Bakker", "Visser",
                "Virtanen", "Korhonen", "Mäkinen", "Nieminen", "Mäkelä",
                "Popescu", "Ionescu", "Dumitru", "Stan", "Gheorghe"
            ]
        },
        albumWords: [
            "Void", "Death", "Dark", "Light", "Shadow", "Eternal", "Chaos",
            "Spirit", "Blood", "Night", "Dawn", "Doom", "Storm", "Fire",
            "Abyss", "Ritual", "Curse", "Soul", "Demon", "Ghost",
            "Throne", "Winter", "Grave", "Hell", "Moon", "Sun", "Witch",
            "Crypt", "Tomb", "Ash", "Dust", "Plague", "Rot", "Ruin",
            "Wraith", "Specter", "Mist", "Fog", "Frost", "Bloodmoon",
            "Cataclysm", "Damnation", "Entropy", "Frostbite", "Grimoire",
            "Hellfire", "Inferno", "Judgement", "Kronos", "Leviathan",
            "Maelstrom", "Nemesis", "Omega", "Purgatory", "Ragnarok",
            "Solitude", "Tempest", "Underworld", "Valhalla", "Wormhole",
            "Xenolith", "Yggdrasil", "Zeitgeist",
            "Ethereal",
            "Celestial",
            "Primordial",
            "Eternal",
            "Arcane",
            "Astral",
            "Cosmic",
            "Divine",
            "Eldritch",
            "Forbidden",
            "Immortal",
            "Infernal",
            "Mystical",
            "Occult",
            "Omnipotent",
            "Spectral",
            "Sublime",
            "Transcendent",
            "Void",
            "Ethereal"
        ],
        albumTitles: [
            "The Suffering Will Never End",
            "Eternal Void of Nothingness",
            "Beneath the Rotting Earth",
            "Summoned from Ancient Graves", 
            "Darkness Consumes All",
            "The Blackened Path to Oblivion",
            "Funeral Procession of the Damned",
            "When Hope Dies",
            "Echoes of a Thousand Screams",
            "Drowning in Infinite Darkness",
            "Blood Moon Rising",
            "Entombed in Frost",
            "The Crushing Weight of Existence",
            "Hymns of the Void",
            "Monoliths of Despair",
            "Caverns of the Ancient Dead",
            "Ritualistic Descent",
            "Crypt of Eternal Sorrow",
            "Throne of Pestilence",
            "Bleak Horizons",
            "Where Light Dies",
            "Forests of the Night",
            "Blacker Than the Blackest Black",
            "Souls Harvested at Dawn",
            "The Reaper's Call",
            "Tombs of the Forgotten",
            "Plague-Ridden Wastelands",
            "Ceremonial Death Worship",
            "Corridors of Torment",
            "Realm of Eternal Frost",
            "Ancient Evil Awakens",
            "The Void Stares Back",
            "Necromantic Rites",
            "Unholy Manifestations",
            "Demonic Incarnations",
            "Sepulchral Depths",
            "Throne of Bones",
            "Sacrificial Blood Moon",
            "Summoning the Elder Gods",
            "Goat Worship Ritual",
            "Possessed by Ancient Evil",
            "Blood Sacrifice at Midnight",
            "Eternal Damnation Awaits",
            "Crypts of Horror",
            "Hell's Eternal Kingdom",
            "Satan's Dark Throne",
            "Blasphemous Communion",
            "Kingdom of the Damned",
            "Infernal Majesty",
            "Streams of Blood",
            "Gates of Hell Unleashed",
            "Demonic Possession",
            "Occult Mysteries",
            "Summoning Ancient Spirits",
            "Dark Web of Existence",
            "Chains of Torment",
            "Visions of Horror",
            "Stories from the Grave",
            "Putrid Existence",
            "Rotting in Darkness",
            "Death's Cold Embrace",
            "Frost-Bitten Souls",
            "Ceremonial Bloodletting",
            "Nocturnal Blasphemy",
            "Funeral Winds",
            "Grave Desecration",
            "Morbid Tales",
            "Pestilential Winds",
            "Decrepit Ruins",
            "Charnel House",
            "Burial Ground",
            "Catacombs of Terror",
            "Sepulchral Silence",
            "Mortuary Descent",
            "Necropolis Rising",
            "Graveyard of Souls",
            "Coffin Nails",
            "Death's Head",
            "Bone Throne",
            "Skull Altar",
            "Witch's Sabbath",
            "Black Mass",
            "Hellfire and Damnation",
            "Lucifer's Light",
            "Morning Star Rising",
            "Goat of Mendes",
            "Baphomet's Call",
            "Pentagram Ritual",
            "Inverted Cross",
            "Unholy Sacrament",
            "Profane Communion",
            "Blasphemous Rites",
            "Demonic Incantation",
            "Infernal Blessing",
            "Diabolical Fullmoon",
            "Moonlit Sacrifice",
            "Midnight Offering",
            "Dark Prophecies",
            "Ancient Curses",
            "Forbidden Knowledge",
            "Occult Wisdom",
            "Grimoire of Shadows",
            "Book of the Dead",
            "Necronomicon Dreams"
        ]
    }
}