console.log('Data.js loading...');

class WikiData {
    static pools = {
        cities: {
            US: [
                // Original cities
                "Portland, Oregon", "Seattle, Washington",
                "Brooklyn, New York", "Austin, Texas", 
                "Chicago, Illinois", "Los Angeles, California",
                "Philadelphia, Pennsylvania", "Oakland, California",
                "Minneapolis, Minnesota", "Providence, Rhode Island",
                "Worcester, Massachusetts", "Richmond, Virginia",
                "Olympia, Washington", "Baltimore, Maryland",
                "New Haven, Connecticut", "Cleveland, Ohio",
                "Detroit, Michigan", "Pittsburgh, Pennsylvania", 
                "Burlington, Vermont", "Asheville, North Carolina",
                // Additional US cities to reach 100+
                "Baton Rouge, Louisiana", "Bellingham, Washington",
                "Bend, Oregon", "Birmingham, Alabama",
                "Bloomington, Indiana", "Boulder, Colorado",
                "Buffalo, New York", "Cambridge, Massachusetts",
                "Cedar Rapids, Iowa", "Columbia, Missouri",
                "Columbia, South Carolina", "Columbus, Georgia",
                "Columbus, Ohio", "Corpus Christi, Texas",
                "Denton, Texas", "Dover, Delaware",
                "El Paso, Texas", "Everett, Washington",
                "Fargo, North Dakota", "Flagstaff, Arizona",
                "Fort Wayne, Indiana", "Gainesville, Florida",
                "Galveston, Texas", "Green Bay, Wisconsin",
                "Greenville, South Carolina", "Honolulu, Hawaii",
                "Houston, Texas", "Huntsville, Alabama",
                "Iowa City, Iowa", "Jackson, Mississippi",
                "Jersey City, New Jersey", "Kalamazoo, Michigan",
                "Key West, Florida", "Laramie, Wyoming",
                "Las Cruces, New Mexico", "Las Vegas, Nevada",
                "Lawrence, Kansas", "Lexington, Kentucky",
                "Lincoln, Nebraska", "Long Beach, California",
                "Lubbock, Texas", "Macon, Georgia",
                "Manchester, New Hampshire", "Mesa, Arizona",
                "Mobile, Alabama", "Modesto, California",
                "Montgomery, Alabama", "Morgantown, West Virginia",
                "Naples, Florida", "Newark, New Jersey",
                "Newport, Rhode Island", "Norfolk, Virginia",
                "Norman, Oklahoma", "Ogden, Utah",
                "Oklahoma City, Oklahoma", "Olympia, Washington",
                "Palm Springs, California", "Pensacola, Florida",
                "Peoria, Illinois", "Phoenix, Arizona",
                "Portland, Maine", "Provo, Utah",
                "Pueblo, Colorado", "Reno, Nevada",
                "Riverside, California", "Roanoke, Virginia",
                "Salem, Oregon", "San Diego, California",
                "Santa Cruz, California", "Santa Fe, New Mexico",
                "Sarasota, Florida", "Scottsdale, Arizona",
                "Shreveport, Louisiana", "Sioux Falls, South Dakota",
                "South Bend, Indiana", "Spokane Valley, Washington",
                "Springfield, Illinois", "St. Paul, Minnesota",
                "St. Petersburg, Florida", "State College, Pennsylvania",
                "Stillwater, Oklahoma", "Tempe, Arizona",
                "Topeka, Kansas", "Traverse City, Michigan",
                "Tyler, Texas", "Vancouver, Washington",
                "Ventura, California", "Virginia Beach, Virginia",
                "Waco, Texas", "Winston-Salem, North Carolina",
                "Yakima, Washington", "Yuma, Arizona",
                "Reykjavik, Iceland",
                "Marrakech, Morocco",
                "Kathmandu, Nepal",
                "Albuquerque, New Mexico",
                "Anchorage, Alaska"
            ]
        },
        genres: {
            metal: [
                // Original genres
                "Death Metal", "Black Metal", "Doom Metal",
                "Sludge Metal", "Post-Metal", "Grindcore",
                "Blackened Crust", "Funeral Doom",
                "Atmospheric Black Metal", "Death-Doom",
                "Technical Death Metal", "Melodic Black Metal",
                "Blackened Death Metal", "Progressive Metal",
                "Stoner Metal", "Drone Metal",
                // Additional metal genres to reach 100+
                "Viking Metal", "Pagan Metal", "War Metal",
                "Brutal Death Metal", "Symphonic Black Metal",
                "Depressive Black Metal", "Raw Black Metal",
                "Ambient Black Metal", "Melodic Death Metal",
                "Technical Thrash Metal", "Crossover Thrash",
                "Speed Metal", "Power Metal", "Epic Metal",
                "Traditional Heavy Metal", "NWOBHM",
                "Groove Metal", "Nu Metal", "Alternative Metal",
                "Industrial Metal", "Electronic Metal",
                "Cyber Metal", "Gothic Metal", "Dark Metal",
                "Symphonic Metal", "Orchestral Metal",
                "Neoclassical Metal", "Medieval Metal",
                "Folk Metal", "Celtic Metal", "Oriental Metal",
                "Pirate Metal", "Battle Metal", "Fantasy Metal",
                "Space Metal", "Cosmic Metal", "Atmospheric Metal",
                "Post-Black Metal", "Shoegaze Metal",
                "Experimental Metal", "Avant-garde Metal",
                "Progressive Death Metal", "Technical Progressive Metal",
                "Djent", "Math Metal", "Extreme Progressive Metal",
                "Blackened Thrash Metal", "Blackened Death Metal",
                "Blackened Doom Metal", "Blackened Speed Metal",
                "Death 'n' Roll", "Groove Death Metal",
                "Melodic Groove Metal", "Southern Metal",
                "Sludge Doom Metal", "Stoner Doom Metal",
                "Desert Rock Metal", "Psychedelic Doom Metal",
                "Occult Metal", "Ritual Metal", "Esoteric Metal",
                "Mystical Metal", "Shamanic Metal",
                "Tribal Metal", "Primitive Metal",
                "Caveman Metal", "Neanderthal Metal",
                "Brutal Technical Death Metal", "Slam Death Metal",
                "Goregrind", "Pornogrind", "Deathgrind",
                "Cybergrind", "Digital Metal", "8-bit Metal",
                "Nintendocore", "Kawaii Metal", "J-Metal",
                "Visual Kei", "Angura Kei", "Melodic Metalcore",
                "Progressive Metalcore", "Technical Metalcore",
                "Deathcore", "Blackened Deathcore",
                "Symphonic Deathcore", "Progressive Deathcore",
                "Technical Deathcore", "Melodic Deathcore",
                "Brutal Deathcore", "Slam Deathcore",
                "Experimental Deathcore", "Avant-garde Deathcore",
                "Electronic Deathcore", "Industrial Deathcore",
                "Cyber Deathcore", "Atmospheric Deathcore",
                "Post-Deathcore", "Blackgaze Deathcore",
                "Doom Deathcore", "Death-Doom Deathcore",
                "Sludge Deathcore", "Stoner Deathcore",
                "Progressive Death-Doom", "Funeral Death-Doom",
                "Blackgaze", "Post-Metal", "Drone", "Sludge", "Mathcore", "Folk Metal", "Industrial", "Symphonic", "Gothic", "Prog", "Tech Death", "Melodeath", "Deathcore", "Crossover", "Thrashcore"
            ],
            experimental: [
                // Original genres
                "Noise Rock", "Industrial", "Drone",
                "Avant-garde Metal", "Progressive Metal",
                "Post-Hardcore", "Math Rock",
                "Experimental Rock", "Power Electronics",
                "Dark Ambient", "Harsh Noise",
                "No Wave", "Free Jazz Metal",
                "Industrial Noise", "Musique Concrète",
                // Additional experimental genres to reach 100+
                "Glitch", "IDM", "Breakcore",
                "Noise Pop", "Art Rock", "Krautrock",
                "Space Rock", "Psychedelic Rock",
                "Avant-prog", "Zeuhl", "RIO",
                "Chamber Rock", "Neo-Classical",
                "Contemporary Classical", "Minimalism",
                "Maximalism", "Spectralism", "Microtonality",
                "Sound Art", "Sound Collage", "Plunderphonics",
                "Vaporwave", "Hauntology", "Hypnagogic Pop",
                "Outsider Music", "Lo-fi", "Field Recordings",
                "Found Sound", "Musique Acousmatique",
                "Electroacoustic", "Live Electronics",
                "Circuit Bending", "Hardware Noise",
                "Harsh Wall Noise", "Ambient Noise",
                "Death Industrial", "Power Electronics",
                "Rhythmic Noise", "Digital Hardcore",
                "Cybergrind", "Japanoise", "Onkyokei",
                "Free Improvisation", "Non-music",
                "Anti-music", "Abstract Music",
                "Reductionism", "Minimalist Improvisation",
                "Extended Technique", "Prepared Instruments",
                "Sound Poetry", "Text-sound Composition",
                "Visual Music", "Graphic Scores",
                "Aleatoric Music", "Chance Music",
                "Process Music", "Generative Music",
                "Algorithm Music", "AI Music",
                "Bio-music", "Eco-acoustic",
                "Acoustic Ecology", "Soundscape Composition",
                "Drone Ambient", "Dark Jazz",
                "Avant-garde Jazz", "Free Jazz",
                "Noise Jazz", "Industrial Jazz",
                "Post-Industrial", "Tribal Industrial",
                "Ritual Ambient", "Death Ambient",
                "Space Ambient", "Cosmic Ambient",
                "Isolationist", "Fourth World",
                "Ethnic Electronica", "Tribal Experimental",
                "Primitive Electronics", "Future Primitive",
                "Neo-Tribal", "Post-Digital",
                "Glitch Ambient", "Microsound",
                "Granular Synthesis", "Drone Metal",
                "Noise Metal", "Avant-garde Metal",
                "Experimental Black Metal", "Abstract Metal",
                "Progressive Electronic", "Berlin School",
                "Kosmische Musik", "Space Music",
                "Xenharmonic", "Just Intonation",
                "Spectral Music", "Drone Folk",
                "Experimental Folk", "Avant-Folk",
                "Freak Folk", "Psychedelic Folk",
                "Noise Folk", "Industrial Folk",
                "Dark Folk", "Apocalyptic Folk",
                "Neo-Folk", "Post-Folk"
            ]
        },
        labels: [
            // Original labels
            "Relapse Records", "Southern Lord", "Profound Lore", "The Flenser",
            "Neurot Recordings", "Hydra Head", "Ipecac Recordings", "Thrill Jockey",
            "Three One G", "Deathwish Inc.", "20 Buck Spin", "Translation Loss",
            "Sargent House", "Sacred Bones", "Gilead Media", "Throatruiner Records",
            "Roadburn Records", "Hypertension Records", "Torture Garden Records",
            "Nuclear War Now!", "Iron Lung Records", "Gravity Records",
            "Alternative Tentacles", "Load Records", "Hospital Productions",
            "Handmade Birds", "Crucial Blast",
            // Additional labels to reach 100+
            "Svart Records", "Prophecy Productions", "Eisenwald",
            "Dark Descent Records", "Blood Music", "I, Voidhanger Records",
            "Fallen Empire Records", "Norma Evangelium Diaboli",
            "Invictus Productions", "Iron Bonehead Productions",
            "Hell's Headbangers", "Hells Headbangers Records",
            "Osmose Productions", "Agonia Records", "Debemur Morti",
            "Code666", "Avantgarde Music", "Aesthetic Death",
            "Cyclic Law", "Cold Spring", "Malignant Records",
            "Tesco Organisation", "Ant-Zen", "Hands Productions",
            "Artoffact Records", "Metropolis Records", "Dependent Records",
            "Cold Meat Industry", "Essence Music", "Crucial Blast",
            "Utech Records", "Aurora Borealis", "Vendetta Records",
            "Grindcore Karaoke", "Robotic Empire", "Magic Bullet Records",
            "Level Plane Records", "Revelation Records", "Bridge Nine Records",
            "Tankcrimes", "Prosthetic Records", "Willowtip Records",
            "Unique Leader", "Sevared Records", "New Standard Elite",
            "Comatose Music", "Gore House Productions", "Lacerated Enemy",
            "Dark Descent Records", "Blood Harvest Records", "Me Saco Un Ojo",
            "Caligari Records", "Invictus Productions", "Dark Symphonies",
            "The Ajna Offensive", "Norma Evangelium Diaboli", "End All Life",
            "Northern Heritage", "Terratur Possessions", "Signal Rex",
            "Amor Fati Productions", "Ván Records", "Urtod Void",
            "Iron Bonehead", "Nuclear War Now!", "Hell's Headbangers",
            "Hells Headbangers", "Osmose Productions", "Season of Mist",
            "Agonia Records", "Debemur Morti", "Code666",
            "Avantgarde Music", "Aesthetic Death", "Cyclic Law",
            "Cold Spring", "Malignant Records", "Tesco Organisation",
            "Ant-Zen", "Hands Productions", "Artoffact Records",
            "Metropolis Records", "Dependent Records", "Cold Meat Industry",
            "Essence Music", "Crucial Blast", "Utech Records",
            "Aurora Borealis", "Vendetta Records", "Grindcore Karaoke",
            "Robotic Empire", "Magic Bullet Records", "Level Plane Records",
            "Revelation Records", "Bridge Nine Records", "Tankcrimes",
            "Prosthetic Records", "Willowtip Records", "Unique Leader",
            "Profound Lore", "Nuclear Blast", "Season of Mist"
        ],
        names: {
            first: [
                // Original names
                "John", "Mike", "David", "Chris", "James",
                "Sarah", "Emma", "Alex", "Sam", "Dan", 
                "Steve", "Tom", "Paul", "Kevin", "Rob",
                "Erik", "Justin", "Ryan", "Matt", "Josh",
                // Additional names to reach 100+
                "Adrian", "Aiden", "Alec", "Andrew", "Anthony",
                "Austin", "Benjamin", "Bradley", "Brandon", "Brett",
                "Bryan", "Caleb", "Cameron", "Chad", "Charles",
                "Chase", "Christian", "Christopher", "Cody", "Colin",
                "Connor", "Corey", "Craig", "Dale", "Damien",
                "Daniel", "Darren", "Derek", "Devin", "Dominic",
                "Douglas", "Drew", "Dustin", "Edward", "Elijah",
                "Ethan", "Evan", "Frank", "Gabriel", "Garrett",
                "Gary", "George", "Grant", "Henry", "Ian",
                "Isaac", "Jack", "Jacob", "Jake", "Jamie",
                "Jared", "Jason", "Jeffrey", "Jeremy", "Jesse",
                "Joel", "John", "Jonathan", "Jordan", "Joseph",
                "Joshua", "Julian", "Justin", "Keith", "Kenneth",
                "Kevin", "Kyle", "Lance", "Larry", "Logan",
                "Lucas", "Luke", "Marcus", "Mark", "Martin",
                "Matthew", "Maxwell", "Michael", "Mitchell", "Nathan",
                "Nicholas", "Noah", "Oliver", "Owen", "Patrick",
                "Peter", "Philip", "Preston", "Randall", "Raymond",
                "Richard", "Robert", "Roger", "Ronald", "Russell",
                "Ryan", "Samuel", "Scott", "Sean", "Seth",
                "Shane", "Shawn", "Stephen", "Steven", "Taylor",
                "Thomas", "Timothy", "Todd", "Travis", "Trevor",
                "Tyler", "Victor", "Vincent", "Walter", "Wayne",
                "Wesley", "William", "Zachary", "Aaron", "Seth"
            ],
            last: [
                // Original last names
                "Smith", "Johnson", "Williams", "Brown", "Jones",
                "Garcia", "Miller", "Davis", "Wilson", "Anderson",
                "Taylor", "Moore", "Jackson", "Martin", "Lee",
                "Thompson", "White", "Harris", "Clark", "Lewis",
                // Additional last names to reach 100+
                "Abbott", "Adams", "Alexander", "Allen", "Anderson",
                "Andrews", "Armstrong", "Arnold", "Bailey", "Baker",
                "Barnes", "Bell", "Bennett", "Black", "Boyd",
                "Bradley", "Brooks", "Bryant", "Burns", "Butler",
                "Campbell", "Carpenter", "Carroll", "Carter", "Chapman",
                "Clark", "Cole", "Coleman", "Collins", "Cook",
                "Cooper", "Cox", "Crawford", "Cruz", "Cunningham",
                "Davidson", "Davies", "Davis", "Day", "Dean",
                "Dixon", "Douglas", "Duncan", "Dunn", "Edwards",
                "Elliott", "Ellis", "Evans", "Ferguson", "Fisher",
                "Fleming", "Fletcher", "Ford", "Foster", "Fox",
                "Freeman", "Gardner", "Gibson", "Gilbert", "Gordon",
                "Graham", "Grant", "Gray", "Green", "Griffin",
                "Hall", "Hamilton", "Hansen", "Harper", "Harrison",
                "Hart", "Harvey", "Hawkins", "Hayes", "Henderson",
                "Henry", "Hernandez", "Hicks", "Hill", "Holmes",
                "Hopkins", "Howard", "Hudson", "Hughes", "Hunt",
                "Hunter", "Jackson", "Jenkins", "Jensen", "Johnson",
                "Johnston", "Jones", "Jordan", "Kelly", "Kennedy",
                "King", "Knight", "Lane", "Lawrence", "Lee",
                "Lewis", "Little", "Long", "Lopez", "Lynch",
                "Marshall", "Martin", "Mason", "Matthews", "McDonald",
                "Meyer", "Miller", "Mills", "Mitchell", "Moore",
                "Morgan", "Morris", "Morrison", "Murphy", "Murray",
                "Nelson", "Newman", "Nielsen", "O'Brien", "O'Connor",
                "Oliver", "Olson", "Palmer", "Parker", "Patterson",
                "Young", "Hall", "Walker"
            ]
        },
        albumWords: [
            // Original words
            "Void", "Death", "Dark", "Light", "Shadow", "Eternal", "Chaos",
            "Spirit", "Blood", "Night", "Dawn", "Doom", "Storm", "Fire",
            "Abyss", "Ritual", "Curse", "Soul", "Demon", "Ghost",
            // Additional words to reach 100+
            "Ancient", "Arcane", "Astral", "Banished", "Blackened",
            "Blasphemy", "Bleeding", "Blighted", "Burning", "Celestial",
            "Chthonic", "Cosmic", "Crimson", "Crucified", "Cryptic",
            "Damned", "Darkness", "Deathless", "Decaying", "Demonic",
            "Desecrated", "Diabolic", "Divine", "Dreadful", "Dying",
            "Eldritch", "Endless", "Eternal", "Evil", "Fallen",
            "Feral", "Forsaken", "Frozen", "Funeral", "Ghastly",
            "Gloomy", "Grim", "Haunted", "Hellish", "Hollow",
            "Howling", "Immortal", "Infernal", "Infinite", "Lost",
            "Lucifer", "Lunar", "Macabre", "Malevolent", "Malignant",
            "Morbid", "Mortal", "Mystic", "Necro", "Nefarious",
            "Nightfall", "Nocturnal", "Occult", "Ominous", "Pagan",
            "Pestilent", "Phantasm", "Possessed", "Profane", "Putrid",
            "Raven", "Rotting", "Ruined", "Sacred", "Savage",
            "Scarred", "Serpent", "Shadowed", "Sinister", "Skeletal",
            "Slaughtered", "Sorcery", "Spectral", "Suffering", "Summoned",
            "Tormented", "Twilight", "Twisted", "Undead", "Unhallowed",
            "Unholy", "Venomous", "Vile", "Wicked", "Withered",
            "Wrath", "Wretch", "Writhing", "Zombie", "Abyssal",
            "Accursed", "Baleful", "Barbaric", "Bestial", "Blasphemous",
            "Bloodied", "Cadaverous", "Catastrophic", "Corrupted",
            "Desolate", "Diabolical", "Doomed", "Draconian", "Ethereal",
            "Throne", "Winter", "Grave", "Caverns of the Ancient Dead", "Ritualistic Descent"
        ],
        albumTitles: [
            // Original titles
            "The Suffering Will Never End",
            "Eternal Void of Nothingness",
            "Beneath the Rotting Earth",
            "Summoned from Ancient Graves", 
            "Darkness Consumes All",
            // Additional titles to reach 100+
            "Abyssal Throne of Eternal Night",
            "Ancient Wisdom of the Damned",
            "Beneath Black Wings of Death",
            "Beyond the Veil of Shadows",
            "Black Flames of Eternal Damnation",
            "Blasphemous Rites of the Dead",
            "Blood Moon Rising Over Ruins",
            "Ceremonial Descent into Madness",
            "Chaos Reigns in Darkness",
            "Chronicles of the Undead",
            "Cosmic Horror Unleashed",
            "Crimson Tides of Destruction",
            "Crown of Thorns and Bones",
            "Cursed Be Thy Kingdom",
            "Dark Prophecies Fulfilled",
            "Death's Eternal Embrace",
            "Descent into the Abyss",
            "Dimensions of Horror",
            "Dominion of the Dark",
            "Echoes from the Void",
            "Eternal Night of the Soul",
            "Everlasting Torment",
            "From Depths Unknown",
            "Funeral March of the Undead",
            "Gates of Hell Unleashed",
            "Ghostly Apparitions",
            "Grave Desecration Ritual",
            "Harbinger of Doom",
            "Haunted by Shadows",
            "In League with Darkness",
            "Infernal Majesty Rising",
            "Into the Mouth of Madness",
            "Kingdom of the Dead",
            "Legacy of Horror",
            "Lords of the Underworld",
            "Malevolent Forces Arise",
            "Manifestations of Evil",
            "Monoliths of Despair",
            "Morbid Tales of Death",
            "Necromantic Rituals",
            "Night of the Blood Moon",
            "Occult Mysteries Revealed",
            "Pantheon of the Ancient Ones",
            "Path to Eternal Darkness",
            "Portal to the Void",
            "Prophecies of Doom",
            "Realm of Shadows",
            "Reign of the Undead",
            "Ritual of the Damned",
            "Sacrificial Offerings",
            "Serpent's Curse",
            "Shadows of Eternity",
            "Signs of the End Times",
            "Slaughter of the Innocent",
            "Souls of the Forgotten",
            "Spectral Visions",
            "Summoning Ancient Evil",
            "Symphony of Horror",
            "Tales from the Crypt",
            "Temple of Death",
            "The Ancient One Awakens",
            "The Art of Necromancy",
            "The Black Flame Burns",
            "The Curse Lives On",
            "The Dark Lord Returns",
            "The Dead Shall Rise",
            "The Final Ritual",
            "The Gates Open Wide",
            "The Last Sacrifice",
            "The Oath of Blood",
            "The Reaper Comes",
            "The Ritual Begins",
            "The Serpent's Kiss",
            "The Summoning",
            "The Unholy Cross",
            "The Witch's Curse",
            "Throne of Bones",
            "Through Gates of Hell",
            "Time of the Witch",
            "Tomb of the Ancients",
            "Tormented Souls",
            "Twilight of the Gods",
            "Under a Blood Moon",
            "Unholy Manifestations",
            "Valley of Death",
            "Visions of Horror",
            "Voice of the Dead",
            "Walpurgisnacht",
            "When Darkness Falls",
            "Where Angels Die",
            "Winds of Death",
            "Witchcraft and Sorcery",
            "Wrath of the Ancient Ones",
            "Written in Blood",
            "Ye Old Black Arts",
            "Zealot's Curse",
            "Caverns of the Ancient Dead", "Ritualistic Descent"
        ]
    }
}